/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package codigo;

import java.awt.Image;
import javax.swing.ImageIcon;
import javax.swing.JButton;

/**
 *
 * @author Guille López
 */
public class VentanaAhorcado extends javax.swing.JFrame {
    
    //Esta variable guarda cuántos fallos llevo en el juego
    int numeroFallos = 0;
    
    //La palabra irá siempre en MAYÚSCULA
    String palabraOculta = "CETYS";
    
    /**
     * Creates new form VentanaAhorcado
     */
    public VentanaAhorcado() {
        initComponents();
        dibujaImagen();
        
    }
    
    //Este método recibe el botón que ha sido pulsado
    //y procesa la letra que tiene en su etiqueta
    private void chequeaBoton( JButton boton){
        boton.setEnabled(false);
        chequeaLetra(boton.getText());
    }

    private void chequeaLetra(String letra){
        String palabraConGuiones = Palabra.getText();
        
        if (palabraOculta.contains(letra)){
            //En este caso la letra si que está y hay que hacer
            //que la o las letras se descubran en la palabra con guiones.
            char letraPulsada = letra.charAt(0);
            for (int i=0; i<palabraOculta.length(); i++){
                if (palabraOculta.charAt(i) == letraPulsada){
                    palabraConGuiones =
                            palabraConGuiones.substring(0, 2*i)
                            + letra
                            + palabraConGuiones.substring(2*i+1);
                }
            }  
            
            Palabra.setText(palabraConGuiones);
            if (!palabraConGuiones.contains("_")){
                numeroFallos = -1;
                dibujaImagen();
            }
        }
        
        else {
            numeroFallos++;
            dibujaImagen();
        }
        
        
    }
            
    //Cambia la imagen en función de cuántos fallos llevamos
    private void dibujaImagen(){
        String nombreImagen = "";
        switch (numeroFallos){
            case -1: nombreImagen = "/imagenes/acertasteTodo.png"; break;
            case 0: nombreImagen = "/imagenes/ahorcado_0.png"; break;
            case 1: nombreImagen = "/imagenes/ahorcado_1.png"; break;
            case 2: nombreImagen = "/imagenes/ahorcado_2.png"; break;
            case 3: nombreImagen = "/imagenes/ahorcado_3.png"; break;
            case 4: nombreImagen = "/imagenes/ahorcado_4.png"; break;
            case 5: nombreImagen = "/imagenes/ahorcado_5.png"; break;
            default : nombreImagen = "/imagenes/ahorcado_fin.png"; break;
        }
        
        ImageIcon miImagen = new ImageIcon(
                    new ImageIcon(getClass().getResource(nombreImagen))
                    .getImage()
                    .getScaledInstance( HombreAhorcado.getWidth(),
                                        HombreAhorcado.getHeight(),
                                        Image.SCALE_DEFAULT)
                
        );
        //Cargo la imagen en el jLabel que muestra que fallo llevamos
        HombreAhorcado.setIcon(miImagen);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        Palabra = new javax.swing.JLabel();
        HombreAhorcado = new javax.swing.JLabel();
        LetraA = new javax.swing.JButton();
        LetraB = new javax.swing.JButton();
        LetraC = new javax.swing.JButton();
        LetraD = new javax.swing.JButton();
        LetraE = new javax.swing.JButton();
        LetraF = new javax.swing.JButton();
        LetraG = new javax.swing.JButton();
        LetraH = new javax.swing.JButton();
        LetraI = new javax.swing.JButton();
        LetraJ = new javax.swing.JButton();
        LetraK = new javax.swing.JButton();
        LetraL = new javax.swing.JButton();
        LetraM = new javax.swing.JButton();
        LetraN = new javax.swing.JButton();
        LetraÑ = new javax.swing.JButton();
        LetraO = new javax.swing.JButton();
        LetraP = new javax.swing.JButton();
        LetraQ = new javax.swing.JButton();
        LetraR = new javax.swing.JButton();
        LetraS = new javax.swing.JButton();
        LetraT = new javax.swing.JButton();
        LetraU = new javax.swing.JButton();
        LetraV = new javax.swing.JButton();
        LetraW = new javax.swing.JButton();
        LetraX = new javax.swing.JButton();
        LetraY = new javax.swing.JButton();
        LetraZ = new javax.swing.JButton();

        jLabel2.setText("jLabel2");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Palabra.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        Palabra.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Palabra.setText("_ _ _ _ _");
        Palabra.setToolTipText("");

        LetraA.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraA.setText("A");
        LetraA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraAActionPerformed(evt);
            }
        });

        LetraB.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraB.setText("B");
        LetraB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraBActionPerformed(evt);
            }
        });

        LetraC.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraC.setText("C");
        LetraC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraCActionPerformed(evt);
            }
        });

        LetraD.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraD.setText("D");
        LetraD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraDActionPerformed(evt);
            }
        });

        LetraE.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraE.setText("E");
        LetraE.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraEActionPerformed(evt);
            }
        });

        LetraF.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraF.setText("F");
        LetraF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraFActionPerformed(evt);
            }
        });

        LetraG.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraG.setText("G");
        LetraG.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraGActionPerformed(evt);
            }
        });

        LetraH.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraH.setText("H");
        LetraH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraHActionPerformed(evt);
            }
        });

        LetraI.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraI.setText("I");
        LetraI.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraIActionPerformed(evt);
            }
        });

        LetraJ.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraJ.setText("J");
        LetraJ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraJActionPerformed(evt);
            }
        });

        LetraK.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraK.setText("K");
        LetraK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraKActionPerformed(evt);
            }
        });

        LetraL.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraL.setText("L");
        LetraL.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraLActionPerformed(evt);
            }
        });

        LetraM.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraM.setText("M");
        LetraM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraMActionPerformed(evt);
            }
        });

        LetraN.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraN.setText("N");
        LetraN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraNActionPerformed(evt);
            }
        });

        LetraÑ.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraÑ.setText("Ñ");
        LetraÑ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraÑActionPerformed(evt);
            }
        });

        LetraO.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraO.setText("O");
        LetraO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraOActionPerformed(evt);
            }
        });

        LetraP.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraP.setText("P");
        LetraP.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraPActionPerformed(evt);
            }
        });

        LetraQ.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraQ.setText("Q");
        LetraQ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraQActionPerformed(evt);
            }
        });

        LetraR.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraR.setText("R");
        LetraR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraRActionPerformed(evt);
            }
        });

        LetraS.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraS.setText("S");
        LetraS.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraSActionPerformed(evt);
            }
        });

        LetraT.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraT.setText("T");
        LetraT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraTActionPerformed(evt);
            }
        });

        LetraU.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraU.setText("U");
        LetraU.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraUActionPerformed(evt);
            }
        });

        LetraV.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraV.setText("V");
        LetraV.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraVActionPerformed(evt);
            }
        });

        LetraW.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraW.setText("w");
        LetraW.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraWActionPerformed(evt);
            }
        });

        LetraX.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraX.setText("X");
        LetraX.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraXActionPerformed(evt);
            }
        });

        LetraY.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraY.setText("Y");
        LetraY.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraYActionPerformed(evt);
            }
        });

        LetraZ.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        LetraZ.setText("Z");
        LetraZ.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                LetraZActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(100, 100, 100)
                                .addComponent(HombreAhorcado, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LetraA, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LetraB, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LetraC, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LetraD, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LetraE, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LetraF, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(LetraG, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LetraH, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LetraI, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LetraJ, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LetraK, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(LetraL, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Palabra, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LetraM, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LetraN, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LetraÑ, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LetraO, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LetraP, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LetraQ, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LetraR, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LetraS, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LetraT, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LetraU, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(LetraV, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(LetraW, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(LetraX, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LetraY, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(LetraZ, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Palabra, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(HombreAhorcado, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LetraA, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LetraB, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LetraC, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LetraD, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LetraE, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LetraF, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LetraG, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LetraH, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LetraI, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LetraJ, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LetraK, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LetraL, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LetraM, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LetraN, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LetraÑ, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LetraO, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LetraP, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LetraQ, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LetraW, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LetraR, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LetraS, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LetraT, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LetraU, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(LetraV, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LetraX, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LetraY, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LetraZ, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void LetraAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraAActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraAActionPerformed

    private void LetraBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraBActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraBActionPerformed

    private void LetraCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraCActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraCActionPerformed

    private void LetraDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraDActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraDActionPerformed

    private void LetraEActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraEActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraEActionPerformed

    private void LetraFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraFActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraFActionPerformed

    private void LetraGActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraGActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraGActionPerformed

    private void LetraHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraHActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraHActionPerformed

    private void LetraIActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraIActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraIActionPerformed

    private void LetraJActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraJActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraJActionPerformed

    private void LetraKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraKActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraKActionPerformed

    private void LetraLActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraLActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraLActionPerformed

    private void LetraMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraMActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraMActionPerformed

    private void LetraNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraNActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraNActionPerformed

    private void LetraÑActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraÑActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraÑActionPerformed

    private void LetraOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraOActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraOActionPerformed

    private void LetraPActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraPActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraPActionPerformed

    private void LetraQActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraQActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraQActionPerformed

    private void LetraRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraRActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraRActionPerformed

    private void LetraSActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraSActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraSActionPerformed

    private void LetraTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraTActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraTActionPerformed

    private void LetraUActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraUActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraUActionPerformed

    private void LetraVActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraVActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraVActionPerformed

    private void LetraWActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraWActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraWActionPerformed

    private void LetraXActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraXActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraXActionPerformed

    private void LetraYActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraYActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraYActionPerformed

    private void LetraZActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_LetraZActionPerformed
        chequeaBoton ((JButton) evt.getSource());
    }//GEN-LAST:event_LetraZActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaAhorcado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaAhorcado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HombreAhorcado;
    private javax.swing.JButton LetraA;
    private javax.swing.JButton LetraB;
    private javax.swing.JButton LetraC;
    private javax.swing.JButton LetraD;
    private javax.swing.JButton LetraE;
    private javax.swing.JButton LetraF;
    private javax.swing.JButton LetraG;
    private javax.swing.JButton LetraH;
    private javax.swing.JButton LetraI;
    private javax.swing.JButton LetraJ;
    private javax.swing.JButton LetraK;
    private javax.swing.JButton LetraL;
    private javax.swing.JButton LetraM;
    private javax.swing.JButton LetraN;
    private javax.swing.JButton LetraO;
    private javax.swing.JButton LetraP;
    private javax.swing.JButton LetraQ;
    private javax.swing.JButton LetraR;
    private javax.swing.JButton LetraS;
    private javax.swing.JButton LetraT;
    private javax.swing.JButton LetraU;
    private javax.swing.JButton LetraV;
    private javax.swing.JButton LetraW;
    private javax.swing.JButton LetraX;
    private javax.swing.JButton LetraY;
    private javax.swing.JButton LetraZ;
    private javax.swing.JButton LetraÑ;
    private javax.swing.JLabel Palabra;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
